### ISSUE TITLE
Hello! this repo still active?

### ISSUE THREAD

**Issue by TylerByte666** [zantdev/yii2-cam-capture#1]
Hi mate, just wondering if this repo is still active?

We would like to start using it... And can it be used as a standalone?

**Comment by zantdev** [comment]
Hi mate, thanks for trying the plugins, it's still active. What do you mean with standalone? Do you wanna use it without plugin extra like yii2-gallery4 and kartik file input?

**Comment by TylerByte666** [comment]
Thanks for the reply mate!

"Do you wanna use it without plugin extra like yii2-gallery4 and kartik file input?"
Yes, that is exactly what we need. Just the webcam feature to yii2
